services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./attack:/srv/attack:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - websocket-server

  app:
    build: ./backend
    expose:
      - "3000"
    # Remove external port mapping since Caddy will proxy
  
  websocket-server:
    build: ./ws
    ports:
      - "3004"
    stdin_open: true
    tty: true

volumes:
  caddy_data:
  caddy_config:
