services:
  app:
    build: ./backend
    ports:
      - "3001:3000"
  attacker:
    image: nginx:alpine
    volumes:
      - ./attack:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
  websocket-server:
    build: ./ws
    ports:
      - "3004:3004"
    stdin_open: true
    tty: true